name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build Administration Service with Maven
      run: mvn -B package --file administration-service/pom.xml
    - name: Build Customer Service with Maven
      run: mvn -B package --file customer-service/pom.xml
    - name: Build Driver Service with Maven
      run: mvn -B package --file driver-service/pom.xml
    - name: Build Registration Service with Maven
      run: mvn -B package --file registration-service/pom.xml
    - name: Build Supplier Service with Maven
      run: mvn -B package --file supplier-service/pom.xml
